### ISSUE TITLE
Exercise 2: Wolf Sleeping and Attr_Reader

### ISSUE THREAD

**Issue by njmullen** [laboon/CS1632_Spring2018#10]
For Exercise 2, wolf.rb contains extra sleep in the initialize method at line 6. Also, wolf_pack.rb does not contain an attr_reader:wolves to access the wolves array.

**Comment by laboon** [comment]
Fixed in commit 41864b67bdc431660e31ea04a409655cbb35461f, please write +2 ISSUE #10 on your D2 cover page for two bonus points
