### ISSUE TITLE
wolf_pack = WolfPack::mew

### ISSUE THREAD

**Issue by lbrennan26** [laboon/CS1632_Spring2018#11]
In wolf_pack.rb, when discussing how to create a wolf pack it should be "new" not "mew"

**Comment by laboon** [comment]
You get extra credit right meow!

Please write +1 ISSUE #11 on your D2 cover sheet for one bonus point.

**Comment by laboon** [comment]
Fixed in commit 5dd6b93da507e188c59a3cde120186805664ec53
