### ISSUE TITLE
Issue with expect() semantics

### ISSUE THREAD

**Issue by aop4** [laboon/CS1632_Spring2018#14]
There was a slight misunderstanding in class about the semantics of the expect() method. It was said that if its second parameter is `true`, a test like that below would pass if the method indicated in the first argument were called, and that if it's `false`, the test would fail if the stubbed method were called. However, the second parameter actually determines what the stubbed method returns, so it cannot be used this way. (The Minitest docs certainly could make this more clear...)

```
mocked_node = Minitest::Mock.new("mocked node")
mocked_node.expect :alone?, true
@g.add_node mocked_node
assert_mock mocked_node
```

**Comment by laboon** [comment]
Announced in class, please write +2 ISSUE #14 on the cover page of your D2 for two bonus points.
