### ISSUE TITLE
+2 ISSUE #20

### ISSUE THREAD

**Issue by zachbugay** [laboon/CS1632_Spring2018#20]
Issue #20
My Pitt Handle: zjb14, Github: zachbugay
Partner Pitt Handle: atd26, Github: adrizos

The hashing algorithm was not clear for D3.

**Comment by laboon** [comment]
Fixed in commit 7d4dfb7a413b628443996acff460c7e943eaee5a

Please write +2 ISSUE #20 on your D3 cover page for 2 bonus points for your group
