### ISSUE TITLE
billcoin.md missing step?

### ISSUE THREAD

**Issue by mho8** [laboon/CS1632_Spring2018#21]
After: Each line consists of one block. A block consists of the following elements, separated by pipes (| characters):

Typo in block order: 1 -> 2 -> 3 -> 5 -> 6

Only 5 blocks, block 5 should contain hash of blocks labeled 1, 2, 3, 5

**Comment by laboon** [comment]
This was a typo, should be 1,2,3,4,5

Fixed in commit fad986c

Please write +1 ISSUE #21 on your D3 cover page for one bonus point for your group
