### ISSUE TITLE
Issue in "deliverable3.md"

### ISSUE THREAD

**Issue by zab31** [laboon/CS1632_Spring2018#22]
"billcoin.rb" should be "billcoin.md", since there is no "billcoin.rb" provided. Issue noticed by Zachary Barlotta and Colton Taylor

**Comment by laboon** [comment]
Fixed in commit 8d9bd0d57adacd3a01e80baf5287e95c850bd9ef

Please write +1 ISSUE #22 on the cover of your D3 deliverable for one bonus point for each member of your group.
