### ISSUE TITLE
Wrong hash in billcoin.md

### ISSUE THREAD

**Issue by yoshino0705** [laboon/CS1632_Spring2018#24]
The hash for the example in billcoin.md:
8|e01d|Sam>John(3):Joe>Sam(4):SYSTEM>Rana(100)|1518839370.605237540|c922

instead of "c922", it should be "c87b"

**Comment by laboon** [comment]
This was a problem with me modifying transactions without modifying hash.  Fixed in commit 6eccb35

Please add +1 ISSUE #24 to cover of D3 for a bonus point
