### ISSUE TITLE
Typo in Exercise 1

### ISSUE THREAD

**Issue by kevinklute** [laboon/CS1632_Spring2018#3]
The [create_arr](https://github.com/laboon/CS1632_Spring2018/blob/0c63d72f9e93d8d9da4d3e086faeb7de9bcf779b/exercises/1/life.rb#L20) method in the exercise 1 starter code creates a `size + 1` by `size + 1` array instead of a `size` by `size` array as specified in the method description.
This is due to `..` being used instead of `...` on lines 22 and 24.

**Comment by laboon** [comment]
Good catch!  Fixed in commit aec5a70.  Please write +2 ISSUE #3 on your deliverable 2 for two bonus points.
