### ISSUE TITLE
+2 ISSUE #35

### ISSUE THREAD

**Issue by zachbugay** [laboon/CS1632_Spring2018#35]
D6 does not specify whether we can simply do Integer Division, or if we must use Floating Point Division with the RPN calculator. 

Can we just use ints for everything, and assume the inputs from user are integers? If they pass a float, can we simply truncate the decimal and use the integer?

**Comment by laboon** [comment]
I sent out an email - please write +2 ISSUE #35 for two bonus points on your D6.

**Comment by laboon** [comment]
Oh to answer your other question, you may assume only int input.  Floating-point input should be considered an error.
