### ISSUE TITLE
D6 Typo?

### ISSUE THREAD

**Issue by yoshino0705** [laboon/CS1632_Spring2018#37]
Under the Automated Test Suite section:
"You do NOT need to run rubocop or simplecov on the test code itself."
But we need to run simplecov on the test code itself to know the coverage... did you mean like "reek" instead of "simplecov"?

**Comment by laboon** [comment]
This might be poorly worded - what I mean is, when considering code coverage via simplecov, ignore any reference to test files.

I am only interested that you have sufficient code coverage of actual production code.
