### ISSUE TITLE
Deliveralbe 6 Program Typo

### ISSUE THREAD

**Issue by cwt11** [laboon/CS1632_Spring2018#38]
Under automated test suite the word program is misspelled to be pogram.

"Your test suite should also (as mentioned above) have >70% statement coverage (as measured by simplecov) of the pogram."

**Comment by laboon** [comment]
OK, fixed in commit 4675d6a.  Kind of a gimme but feel free to write +1 ISSUE #38 on your D6 for one bonus point.
