### ISSUE TITLE
Midterm #2 Study Guide

### ISSUE THREAD

**Issue by Jahanobik234** [laboon/CS1632_Spring2018#39]
Under Security Testing, I'm under the impression that "XSS" should be "CSS" for Cross Site Scripting.

**Comment by laboon** [comment]
You would think so, but nope.  Probably because CSS was already taken for "cascading style sheets".

Proof via wikipedia: https://en.wikipedia.org/wiki/Cross-site_scripting

**Comment by Jahanobik234** [comment]
My apologies!
