### ISSUE TITLE
Missing TA info

### ISSUE THREAD

**Issue by sumanyugupta** [laboon/CS1632_Spring2018#4]
Deliverable 2 [instructions](https://github.com/laboon/CS1632_Spring2018/blob/master/deliverables/2/deliverable2.md) do not have a TA's username listed for the Tuesday/Thursday lecture.
[Course info](https://github.com/laboon/CS1632_Spring2018/blob/master/course-info.md) does not have any TA information listed at all.

**Comment by laboon** [comment]
This information is coming soon - the Tue/Thu TA wanted to make a separate account for grading duties.  I will close this repo when it goes live (should be before D2 is "officially" assigned)

**Comment by laboon** [comment]
Posted!

**Comment by laboon** [comment]
Even though this wasn't an officially posted assignment I will still give you +1 bonus.  Please write "+1 Issue #4" on the cover sheet of D2.
