### ISSUE TITLE
Defect in create_arr in life.rb

### ISSUE THREAD

**Issue by jaf177** [laboon/CS1632_Spring2018#5]
create_arr should have:
arr[x][y] = prng.rand(101) <= percent
ACTUALLY has:
arr[x][y] = prng.rand(101) < percent

**Comment by laboon** [comment]
Good catch!  Fixed in commit 8c01bdb60296e3ed2769e22bba5f74fec176ea25

Please write +2 ISSUE #5 on the cover page of your deliverable 2 for 2 bonus points.
