### ISSUE TITLE
Missing Neighbor in exercise1.md

### ISSUE THREAD

**Issue by mho8** [laboon/CS1632_Spring2018#6]
Last example of neighbors views as:
```
 01234
0n..nX
1n..nn
2.....
3.....
4...nn
```
But should include one additional neighbor at (4,0):
```
 01234
0n..nX
1n..nn
2.....
3.....
4n..nn
```

**Comment by laboon** [comment]
Good catch!  Fixed in commit 6dab96a2c5c10798a60e27ced4c61dbf48c38201.  Please write +2 ISSUE #6 on your second deliverable for two bonus points.
