### ISSUE TITLE
typo in ex1 description

### ISSUE THREAD

**Issue by jondyer** [laboon/CS1632_Spring2018#7]
One of the earlier paragraphs has a typo in the final sentence (should be "an" instead of "and").

> The program shall accept three arguments: size (size of the 2-D array - the number of rows and columns should always be equal, an integer > 0), percentage to be randomly assigned to be living (an integer between 0 and 100 inclusive), and the number of iterations to run (**and** integer >= 0).

**Comment by laboon** [comment]
Good catch!  Fixed in commit b735e1a.  Please write +1 ISSUE #7 on the cover page of your deliverable 2 for one bonus point.
