### ISSUE TITLE
Incorrect command to run multiple Ruby (test) files

### ISSUE THREAD

**Issue by aop4** [laboon/CS1632_Spring2018#9]
SUMMARY: The command that deliverable2.md indicated should be used to run multiple Ruby test files runs only one.
DESCRIPTION: The command `ruby *_test.rb` does not execute all files ending in "_test.rb", but only one of them.
REPRODUCTION STEPS: Make two Ruby files, one called `a_test.rb` and one called `b_test.rb`, each containing a print statement. Ensure there are no other files ending with  "_test.rb" in the current directory. Run `ruby *_test.rb`.
EXPECTED BEHAVIOR: Both files are run.
OBSERVED BEHAVIOR: Only one file is run.

Note: This is just being filed as a formality. deliverable2.md has been revised with a solution to this issue.

**Comment by laboon** [comment]
Fixed in commit 61d582f7cf4653bf781bc942b136547b7fca98d2, remember to mark down +2 ISSUE #9 on your cover sheet for D2
